language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install . --use-mirrors

script: python centidb_test.py

notifications:
  email: false
